### ISSUE TITLE
Getting reference error when using getCurrentUser.

### ISSUE THREAD

**Issue by tofagerl** [mojio/mojio-js#2]
Stack: 
```
ReferenceError: get is not defined
    at MojioClient.module.exports.MojioClient.getCurrentUser (/Users/tom/Dropbox/docs/dev/node.js/ooh/demo/node_modules/mojio-js/lib/nodejs/MojioClient.js:679:9)
    at Object.getUser (/Users/tom/Dropbox/docs/dev/node.js/ooh/demo/lib/mojio.js:48:15)
    at Context.<anonymous> (/Users/tom/Dropbox/docs/dev/node.js/ooh/demo/test/mojio.js:23:9)
    at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:390:10)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:473:12
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:315:14)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:325:7
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:358:17)```

**Comment by robblovell** [comment]
This is fixed after version 3.4.0
